
SELECT * FROM member;

ALTER TABLE member MODIFY name VARCHAR2(30);
ALTER TABLE member MODIFY userid VARCHAR2(30);
ALTER TABLE member MODIFY pwd VARCHAR2(30);
ALTER TABLE member MODIFY email VARCHAR2(30);
ALTER TABLE member MODIFY phone VARCHAR2(30);
